language: objective-c
notifications:
  email:
    on_success: never
    on_failure: change
before_script:
- ./script/add-key
- ./script/set-env
script:
- ./script/build
# - ./script/run-ci-specs
after_script: ./script/remove-key
cache:
  directories:
    - build/node_modules
